# cloudbuild.yaml for building vertx-template with Postgres DB in GCB


# Credential of SourceClear is encrypted using Google Cloud KMS

secrets:
- kmsKeyName: projects/spinnaker-poc-200412/locations/global/keyRings/source-clear-encryption/cryptoKeys/source-clear-encryption
  secretEnv:
    SRCCLR_API_TOKEN: CiQAxgges9eJ3Ae+K0ncF0O/Mb5dtAu/2ZBxHBHuBxwBQ0bjI14SyQMAnnQB+oQeOtj+xlIMzYOy7gYjHz+NNEvXbCkD4rru22WxriP5uD2By/GAyfh7zayMmQrPGfMpEiIv3D4RvEETYvvctUctG7p52axoSBmndCbe8FYyAgOZL7xcTf4XuHijtvYWLDKoKM7CggANss0hKRmvKnSCfYRRffE18bzIcYygCnx0QdlfF6WXJZZxIxP4CuklJkaU0CiQzYUKrY5OsNxnue/YiWkaexaPkZhnwpC/xGMzOfUNSMFhe70Zqas7ZGR8pzEPaRy1C//qoVsOkqKyxBCqW+LfFLPVic/UlmnKo0lWySDGhvY1XzNQeU8u2hE05zggg0xjCi7q5mw5XcuutcktGx2AMtT7gZplwHBz6sOIn/4gP+7SzuQtmjRHxBwAgMXcqKhYSPy2COC6Vq1ODb0otpdLc09Tqd+1FAOKOLRQ6rPKDKPqviUEgemaaTQWMrcdBNP2YbqgK8U2RXL2uc2/49bU3TpjFbAonzMD9gaCvMw/d3CK3yDDu44NTZEiuldO3R01CwbbkAz5gp7MYUtMBHAeATKvhPFW1dSv9EJML0+j7ldROVYuXbOx6UO3xy87dyDg7e50C3i8UQkpsZ8PgTuX

# Build Steps:
# 1. This build step uses docker-compose custom image based on gcr.io/cloud-builders/mvn and invokes a shell script "docker-compose.sh" which launches dbserver and appserver services using docker-compose. The dbserver service is a Postgres container and appserver service runs mvn commands.

# 2. Building GCR image with JAR artifacts.

# Note: Edited sample.properties for Postgres
# Note: docker-compose.yml is used by docker-compose in "docker-compose.sh" in Build Step 1
# Note: "check_postgres_table.sh" is used in "docker-compose.sh"  to verify creation of tables in Postgres DB.
# Note: Dockerfile is used in step 2 to build GCR image with JAR artifacts

steps:
- name: 'gcr.io/spinnaker-poc-200412/github-nikesh-mahalka-2-container-builder-docker-compose:latest'
  entrypoint: 'bash'
  args: ['-c', './docker-compose.sh']
  secretEnv: ['SRCCLR_API_TOKEN']
  env: ['DB_VER=9.3','DB_USR=test','DB_PASS=test','DB_NAME=test','DB_URL=dbserver.workspace_default']
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/vertx-template-gcb:latest", "."]

images:
  - 'gcr.io/$PROJECT_ID/vertx-template-gcb:latest'
