# cloudbuild.yaml for building vertx-template with Oracle DB/ Postgres DB in GCB


# Encrypted SourceClear and Docker Store secrets using Google Cloud KMS
# Docker Store secret in used for Oracle DB
secrets:
- kmsKeyName: projects/spinnaker-poc-200412/locations/global/keyRings/source-clear-encryption/cryptoKeys/source-clear-encryption
  secretEnv:
    SRCCLR_API_TOKEN: CiQAxgges9eJ3Ae+K0ncF0O/Mb5dtAu/2ZBxHBHuBxwBQ0bjI14SyQMAnnQB+oQeOtj+xlIMzYOy7gYjHz+NNEvXbCkD4rru22WxriP5uD2By/GAyfh7zayMmQrPGfMpEiIv3D4RvEETYvvctUctG7p52axoSBmndCbe8FYyAgOZL7xcTf4XuHijtvYWLDKoKM7CggANss0hKRmvKnSCfYRRffE18bzIcYygCnx0QdlfF6WXJZZxIxP4CuklJkaU0CiQzYUKrY5OsNxnue/YiWkaexaPkZhnwpC/xGMzOfUNSMFhe70Zqas7ZGR8pzEPaRy1C//qoVsOkqKyxBCqW+LfFLPVic/UlmnKo0lWySDGhvY1XzNQeU8u2hE05zggg0xjCi7q5mw5XcuutcktGx2AMtT7gZplwHBz6sOIn/4gP+7SzuQtmjRHxBwAgMXcqKhYSPy2COC6Vq1ODb0otpdLc09Tqd+1FAOKOLRQ6rPKDKPqviUEgemaaTQWMrcdBNP2YbqgK8U2RXL2uc2/49bU3TpjFbAonzMD9gaCvMw/d3CK3yDDu44NTZEiuldO3R01CwbbkAz5gp7MYUtMBHAeATKvhPFW1dSv9EJML0+j7ldROVYuXbOx6UO3xy87dyDg7e50C3i8UQkpsZ8PgTuX
    #DOCKER_LOGIN: CiQAxgges7DOxqkgtgOuOMALZgIaa9f1JiSno67g6Lol98O5nocSNACedAH6lqExDVBta0bn8WLD+XqAwhLapJxt4mMxzm6waV8t3js8eSV2PswjVb8DDNWWGxE=

# Build Steps:
# 1. ojdbc7.jar is copied from Google Cloud Storage bucket to GCB workspace for
#    using local maven repository to get the ojdbc7.jar dependency
# 2. Private GCR docker-compose image is used which is built from GCR "gcr.io/cloud-builders/mvn" image
#    and "docker-compose.sh" is run.
# 3. Building GCR image with application jar

# Note: Edited sample.properties for Oracle/Postgres and enabled/disabled ojdbc7 dependency in pom.xml
# Note: docker-compose.yml is used by docker-compose in "docker-compose.sh" in Build Step 2
# Note: "check_oracle_table.sh" / "check_postgres_table.sh" is used in "docker-compose.sh" for clean operation
# Note: Dockerfile is used in step 3 to build GCR image with application jar

steps:
#- name: gcr.io/cloud-builders/gsutil
#  args: ['cp', 'gs://delete-oracle-jdbc-jar/ojdbc7.jar', 'ojdbc7.jar']
- name: 'gcr.io/spinnaker-poc-200412/github-nikesh-mahalka-2-container-builder-docker-compose:latest'
  entrypoint: 'bash'
  args: ['-c', 'chmod 755 ./docker-compose.sh; ./docker-compose.sh']
  # For Postgres DB
  secretEnv: ['SRCCLR_API_TOKEN']
  # For Oracle DB
  # secretEnv: ['SRCCLR_API_TOKEN', 'DOCKER_LOGIN']
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "gcr.io/$PROJECT_ID/vertx-template-gcb:latest", "."]

images:
  - 'gcr.io/$PROJECT_ID/vertx-template-gcb:latest'
