version: '3'

# --------------------------- For Oracle DB -----------

#services:
#  dbserver:
#    image: store/oracle/database-enterprise:12.2.0.1-slim
#    container_name: dbserver
#    volumes:
#      - /workspace:/workspace
#    ports:
#      - "1521:1521"
#  appserver:
#    image: gcr.io/cloud-builders/mvn
#    container_name: appserver
#    environment:
#    - SRCCLR_API_TOKEN=$SRCCLR_API_TOKEN
#    volumes:
#      - /workspace:/workspace
#    entrypoint: |
#      bash -c "apt-get update; apt-get install curl -y; cd /workspace; mvn install:install-file -Dfile=./ojdbc7.jar -DgroupId=com.oracle.jdbc -DartifactId=ojdbc7 -Dversion=12.1.0.2 -Dpackaging=jar; mvn -DskipTests clean package; curl -sSL https://download.sourceclear.com/ci.sh | sh; nohup java -Ddatabase.url=jdbc:oracle:thin:@dbserver.workspace_default:1521/ORCLCDB.localdomain -Djava.security.egd=file:/dev/./urandom -jar ./target/vertx-*-SNAPSHOT.jar create-database run 2>&1 &"
#    depends_on:
#      - dbserver


# ---------------------- For Postgres DB --------------------

services:
  dbserver:
    image: postgres
    container_name: dbserver
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: test
    volumes:
      - /workspace:/workspace
  appserver:
    image: gcr.io/cloud-builders/mvn
    container_name: appserver
    environment:
    - SRCCLR_API_TOKEN=$SRCCLR_API_TOKEN
    volumes:
      - /workspace:/workspace
    entrypoint: |
      bash -c "apt-get update; apt-get install curl -y; cd /workspace; mvn -DskipTests -Ppostgres clean package; curl -sSL https://download.sourceclear.com/ci.sh | sh; nohup java -jar ./target/vertx-*-SNAPSHOT.jar create-database run 2>&1 & sleep 1"
    depends_on:
      - dbserver

